//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axie.SanShare.Persistence.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoninSLP
    {
        public long RecordId { get; set; }
        public System.DateTime DateBatchCode { get; set; }
        public string RoninID { get; set; }
        public string Name { get; set; }
        public Nullable<long> MMR { get; set; }
        public Nullable<long> WalletSLP { get; set; }
        public Nullable<long> InGameSLP { get; set; }
        public Nullable<System.DateTime> LastClaimDate { get; set; }
        public Nullable<System.DateTime> NextClaimDate { get; set; }
        public Nullable<long> TotalSLP { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> RawSLPTotalYesterday { get; set; }
        public Nullable<long> RawSLPDailyYesterday { get; set; }
    }
}
