//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axie.SanShare.Persistence.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarProfile
    {
        public long ScholarRecordId { get; set; }
        public string ScholarName { get; set; }
        public string RoninAddress { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<double> ShareManagerPercentage { get; set; }
        public Nullable<double> ShareScholarPercentage { get; set; }
        public string MarketPlaceEmail { get; set; }
        public string MarketPlacePassword { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
